Modify `build.gradle` to add `rabbitmq` dependency.

[source,java]
.analytics/build.gradle
----
dependencies {
    ...
    ..
    .
include::{sourceDir}/analytics/build.gradle[tag=rabbitmq]
}
----

### Create RabbitMQ exchange, queue and binding

As we already did in Books Microservice, let's create the class `ChannelPoolListener.java` to define the exchange, queue
and binding:

[source,java]
.analytics/src/main/java/example/micronaut/analytics/ChannelPoolListener.java
----
include::{sourceDir}/analytics/src/main/java/example/micronaut/analytics/ChannelPoolListener.java[]
----

TIP: Instead of copy-paste the class in every project it would be better to create a new Gradle (or Maven) module and
share it among all the microservices.


### Create RabbitMQ consumer

Create a new class to act as a consumer of the messages sent to RabbitMQ by the Books Microservice. Micronaut will
implement the consume at compile time. Create `AnalyticsListener.java`

[source,java]
.analytics/src/main/java/example/micronaut/analytics/AnalyticsListener.java
----
include::{sourceDir}/analytics/src/main/java/example/micronaut/analytics/AnalyticsListener.java[]
----
<1> The RabbitMQ listener will not be available for tests.
<2> Annotate the class with `@RabbitListener` to indicate that this bean will consume messages from RabbitMQ.
<3> Constructor injection for `AnalyticsService`.
<4> Annotate the method with `@Queue`. This listener will listen to message in `analytics` queue.
<5> Call the previously created method to update the analytics for the book.
