Modify `build.gradle` to add `rabbitmq` dependency.

[source,java]
.books/build.gradle
----
dependencies {
    ...
    ..
    .
include::{sourceDir}/books/build.gradle[tag=rabbitmq]
}
----

By default Micronaut will connect to a RabbitMQ instance running on `localhost` so it is not necessary to add anything
to `application.yml`. In case you want to change the configuration, add the following:

[source,yaml]
.books/src/main/resources/application.yml
----
rabbitmq:
    uri: amqp://localhost:5672
----

### Create RabbitMQ exchange, queue and binding

Before being able to send and receive messages using RabbitMQ it is necessary to define the exchange, queue and binding.
One option is create them directly in the RabbitMQ Admin UI available on `http://localhost:15672`. Use `guest` for both
username and password.

Another option is create them programatically with Micronaut. Create the class `ChannelPoolListener.java`:

[source,java]
.books/src/main/java/example/micronaut/books/ChannelPoolListener.java
----
include::{sourceDir}/books/src/main/java/example/micronaut/books/ChannelPoolListener.java[]
----
<1> Define an exchange named `micronaut`. From the producer point of view everything is sent to the exchange with the
appropriate routing key
<2> Define a queue named `analytics`. The consumer will listen for messages in that queue.
<3> Define a binding between the exchange, the queue with the routing key `analytics`.


### Create RabbitMQ client (producer)

Let's create an interface to send messages to RabbitMQ. Micronaut will implement the interface at compilation time:

[source,java]
.books/src/main/java/example/micronaut/books/AnalyticsClient.java
----
include::{sourceDir}/books/src/main/java/example/micronaut/books/AnalyticsClient.java[]
----
<1> Set the exchange used to send the messages.
<2> Set the routing key.
<3> Send the `Book` POJO. Micronaut will automatically convert it to JSON before sending it.


### Send Analytics information automatically

Sending a message to RabbitMQ is as simple as injecting `AnalyticsClient` and calling `updateAnalytics` method. The goal
is to do it automatically every time a book is returned, i.e., there is a call to `http://localhost:8080/books/{isbn}`.
The achieve this we are going to create an https://docs.micronaut.io/latest/guide/index.html#filters[Http Server Filter].
Create the file `AnalyticsFilter.java`:

[source,java]
.books/src/main/java/example/micronaut/books/AnalyticsFilter.java
----
include::{sourceDir}/books/src/main/java/example/micronaut/books/AnalyticsFilter.java[]
----
<1> Annotate the class with `@Filter` and define the ANT Matcher pattern to intercept all the call to the desire URI.
<2> The class needs to implement `HttpServerFilter`.
<3> Constructor injection for RabbitMQ `AnalyticsClient`.
<4> Override `doFilter` method.
<5> Execute the request. This will call the controller action.
<6> Get the response from the controller and return the body as a `Book`.
<7> If the book is found, use RabbitMQ client to send a message.
